<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-T3C9NJIV" name="com.leafBot.testcases.TC004_EditLead" tests="1" failures="0" timestamp="01 Feb 2020 05:29:36 GMT" time="12.773" errors="1">
  <testcase name="editLead" time="12.773" classname="com.leafBot.testcases.TC004_EditLead">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:303)
at com.aventstack.extentreports.ExtentTest.pass(ExtentTest.java:524)
at utils.Reporter.reportStep(Reporter.java:57)
at utils.Reporter.reportStep(Reporter.java:64)
at com.leafBot.selenium.api.base.SeleniumBase.clearAndType(SeleniumBase.java:91)
at com.leafBot.pages.LoginPage.enterUserName(LoginPage.java:41)
at com.leafBot.testcases.TC004_EditLead.editLead(TC004_EditLead.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- editLead -->
</testsuite> <!-- com.leafBot.testcases.TC004_EditLead -->
